name       : python-cachy
version    : 0.3.0
release    : 1
source     :
    - https://pypi.io/packages/source/c/cachy/cachy-0.3.0.tar.gz : 186581f4ceb42a0bbe040c407da73c14092379b1e4c0e327fdb72ae4a9b269b1
license    : MIT
component  : programming.python
summary    : Cachy provides a simple yet effective caching library.
description: |
    Cachy provides a simple yet effective caching library.
build      : |
    %python3_setup
install    : |
    %python3_install
    # ...
    rm -r $installdir/usr/lib/python%python3_version%/site-packages/tests/
